# render.yaml
services:
  - type: web
    name: fastapi-lms
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: 222002
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: library_db
